## ADP binding to pyruvate kinase. 

```{python}
#| code-fold: true
import matplotlib.pyplot as plt
import numpy as np
from fysisk_biokemi.widgets import DataUploader
from IPython.display import display 
import pandas as pd
from scipy.optimize import curve_fit
pd.set_option('display.max_rows', 6)
```

Based on the literature, you suspect that the binding of ADP to the enzyme pyruvate kinase might be coopera-tive and decide to investigate this by measuring the binding to the enzyme using radioactive ATP. The enzyme concentration was 4 μM throughout the titration, and each measurement was done in triplicate. The binding results were obtained at 310 K and are given in the `.csv`-file `adp-bindin-pyruva-kinase.csv`. 

::: {.callout-note}

When downloading the `.csv`-file you can right click and choose "Save link as".

::: 

#### (a) Load the dataset

As always, use the widget to load the dataset

```{python}
#| eval: false
uploader = DataUploader()
uploader.display()
```

Run the next cell **after** uploading the file

```{python}
#| eval: false
df = uploader.get_dataframe()
display(df)
```

```{python}
#| solution: true
from fysisk_biokemi.datasets import load_dataset
df = load_dataset('adp_pyruvate') # Load from package for the solution so it doesn't require to interact.
display(df)
```

#### (b) Units

The concentrations in the dataset are given in mM, add a new column to the `DataFrame` 
with the units given in M. 

```{python}
#| exercise: true
#| eval: false
## Your task: Calculate the concentration in M and add it to the dataframe. ##
df['[ADPtot](M)'] = ...
display(df)
```

```{python}
#| solution: true
## Your task: Calculate the concentration in M and add it to the dataframe. ##
df['[ADPtot](M)'] = df['[ADPtot](mM)'] * 10**(-3)
display(df)
```

#### (c) Free ADP concentration 

For each value of $\bar{n}$ calculate the concentration of [ADP$_\text{free}$] from [ADP$_\text{tot}$] and [enzyme].

```{python}
#| exercise: true
#| eval: false

## Your task: Set the enzyme concentration in the variable enzyme_conc
## Use that and the df['[ADPtot](M)'] and df['nbar'] columns to conc. of free ADP.
enzyme_conc = ... # Unit: M
df['[ADPfree](M)'] = ...
display(df)
```

```{python}
#| solution: true

## Your task: Set the enzyme concentration in the variable enzyme_conc
## Use that and the df['[ADPtot](M)'] and df['nbar'] columns to conc. of free ADP.
enzyme_conc = 4 * 10**(-6) # Unit: M
df['[ADPfree](M)'] = df['[ADPtot](M)'] - df['nbar'] * enzyme_conc
display(df)
```

#### (d) Make a plot

Make a plot of the free ligand concentration versus $\bar{n}$. 

```{python}
#| exercise: true
#| eval: false
fig, ax = plt.subplots()

## Your task: Plot [ADfree](M) vs. nbar as a scatter plot
ax.plot(..., ..., 'o')
```

```{python}
#| solution: true
fig, ax = plt.subplots()

## Your task: Plot [ADfree](M) vs. nbar as a scatter plot
ax.plot(df['[ADPfree](M)'], df['nbar'], 'o')

## EXTRA: You do not need to understand this.
## Customization:
ax.set_xlabel(r'$[\text{ADP}_{\text{free}}]$', fontsize=14)
ax.set_ylabel(r'$\bar{n}$', fontsize=14)
```

#### (f) Preparing for fitting

To fit we need a implement the function we want to fit the parameters of, the functional 
form is 

$$
n = n_{\text{max}} \frac{[L]^h}{K_D + [L]^h}
$$

```{python}
#| exercise: true
#| eval: false
def n_bound(L, n_max, K_D, h):
    ## Your task: Implement the function ## 
    result = ...
    return ...

## Your task: Check that these give the outputs they are supposed to.
print(n_bound(1, 1, 1, 1)) # Should give 0.5
print(n_bound(21, 47, 2.5, 1)) # Should give 42.0
print(n_bound(21, 47, 2.5, 2)) # Should give 46.73..
```

```{python}
#| solution: true
def n_bound(L, n_max, K_D, h):
    ## Your task: Implement the function ## 
    result = n_max * L**h / (K_D + L**h)
    return result

## Your task: Check that these give the outputs they are supposed to.
print(n_bound(1, 1, 1, 1)) # Should give 1/2
print(n_bound(21, 47, 2.5, 1)) # Should give 42.0
print(n_bound(21, 47, 2.5, 2)) # Should give 46.73..
```

#### (e) Fitting

Now we want to use regression to find the biochemical parameters $K_D$, $n_\mathrm{max}$ and $h$. 

```{python}
#| exercise: true
#| eval: false

## Your task: Select the data from the dataframe. ##
x = ...
y = ...

## Your task: Make initial guesses for each of the three parameters ##
K_D_guess = ... # Your initial guess for K_D 
n_max_guess = ... # Your initial guess for nu_max
h_guess = ... # Your initial guess for the exponent.

initial_guess = [K_D_guess, n_max_guess, h_guess]

## This limit the parameters to be positive
## This fit can be difficult otherwise.
bounds = [0, np.inf]

# Curve fit
fitted_parameters, trash = curve_fit(n_bound, x, y, initial_guess, bounds=bounds)

# Print the parameters
n_max_fit, K_D_fit, h_fit = fitted_parameters
print(n_max_fit)
print(K_D_fit)
print(h_fit)
```

```{python}
#| solution: true

## Your task: Select the data from the dataframe. ##
x = df['[ADPfree](M)']
y = df['nbar']

## Your task: Make initial guesses for each of the three parameters ##
K_D_guess = 1*10**(-3) # Your initial guess for K_D 
n_max_guess = 2 # Your initial guess for nu_max
h_guess = 3 # Your initial guess for the exponent.

initial_guess = [K_D_guess, n_max_guess, h_guess]

# This limit the parameters to be positive
bounds = [0, np.inf]

# Curve fit
## This fit can be difficult otherwise.
fitted_parameters, trash = curve_fit(n_bound, x, y, initial_guess, bounds=bounds)

# Print the parameters
n_max_fit, K_D_fit, h_fit = fitted_parameters
print(n_max_fit)
print(K_D_fit)
print(h_fit)
```

Once we've obtained the fitted parameters we can plot the fit together with 
the data. 

```{python}
#| exercise: true
#| eval: false

## As usual we evaluate the fitted function ##
L = np.linspace(0, 1.2 * x.max(), 50)
n = n_bound(L, n_max_fit, K_D_fit, h_fit)

## Dont worry about the details of this plot is made ##
fig, ax = plt.subplots(figsize=(7, 4))
ax.plot(df['[ADPfree](M)'], df['nbar'], 'o', label='Observations')
ax.plot(L, n)
ax.axvline(K_D_fit, color='k', linewidth=0.5, linestyle='--')
ax.axhline(n_max_fit, color='k', linewidth=0.5, linestyle='--')
ax.set_xlabel(r'$[\text{ADP}_{\text{free}}]$', fontsize=14)
ax.set_ylabel(r'$\bar{n}$', fontsize=14);
```

```{python}
#| solution: true

## As usual we evaluate the fitted function ##
L = np.linspace(0, 1.2 * x.max(), 50)
n = n_bound(L, n_max_fit, K_D_fit, h_fit)

## Dont worry about the details of this plot is made.
fig, ax = plt.subplots(figsize=(7, 4))
ax.plot(df['[ADPfree](M)'], df['nbar'], 'o', label='Observations')
ax.plot(L, n)
ax.axvline(K_D_fit, color='k', linewidth=0.5, linestyle='--')
ax.axhline(n_max_fit, color='k', linewidth=0.5, linestyle='--')
ax.set_xlabel(r'$[\text{ADP}_{\text{free}}]$', fontsize=14)
ax.set_ylabel(r'$\bar{n}$', fontsize=14);
```

#### (f) Cooperative or not? 

Based on the biochemical parameters you've found and the plot above answer the question is the binding cooperative? 

#### (g) Free energy

Calculate the free energy for the association of the ADP-pyruvate kinase complex assuming $R = 8.314472 \times 10^{-3} \ \frac{\text{kJ}}{\text{mol} \cdot \text{K}}$  and $T = 310 \ \text{K}$. 

::: {.callout-tip}
Consider the difference between association and dissociation
:::

Start by defining the two given constants as variables

```{python}
#| exercise: true
#| eval: false

## Your task: Assign the known values to variables. 
## Its a good idea to add a comment with the units e.g. # kJ/(mol K)
R = ... # kJ/(mol K)
T = ...
```

```{python}
#| solution: true

## Your task: Assign the known values to variables. 
## Its a good idea to add a comment with the units e.g. # kJ/(mol K)
R = 8.314472 * 10**(-3) # kJ/(mol K)
T = 310 # K
```

And do the calculation

```{python}
#| exercise:
#| eval: false

## Your task: Calculate ΔG
## Again its a good idea to add the unit as a comment.
delta_G = ... 
print(delta_G)
```

```{python}
#| solution: true

## Your task: Calculate ΔG
delta_G = R * T * np.log(K_D_fit) # kJ/mol
print(delta_G)
```