## Analysis of a data set obeying Michaelis-Menten kinetics

```{python}
#| code-fold: true
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
from fysisk_biokemi.widgets import DataUploader
from IPython.display import display 
pd.set_option('display.max_rows', 6)
```

The kinetics for an enzyme were investigated using the absorbance of the product 
to calculate the initial velocities for a range of different initial concentrations
of the substrate. The data given in the dataset `analys-data-set-obeyin.xlsx` was obtained. 
Use these data to answer the following questions.

```{python}
#| eval: false
uploader = DataUploader()
uploader.display()
```

Run the next cell **after** uploading the file

```{python}
#| eval: false
df = uploader.get_dataframe()
display(df)
```

```{python}
#| solution: true
from fysisk_biokemi.datasets import load_dataset
df = load_dataset('week49_2') # Load from package for the solution so it doesn't require to interact.
display(df)
```

#### (a) SI Units
Convert the concentrations of substrate and the velocities to the SI units 
$\text{M}$ and $\text{M}\cdot\text{s}^{-1}$, respectively.

```{python}
#| exercise: true
#| eval: false

## Your task: Add new columns with both properties in proper SI units. 
## Use the column names: '[S]_(M)' and 'V0_(M/s)'
...
...
display(df)
```

```{python}
#| solution: true

## Your task: Add new columns with both properties in proper SI units. 
## Use the column names: '[S]_(M)' and 'V0_(M/s)'
df['[S]_(M)'] = df['[S]_(mM)'] * 10**(-3)
df['V0_(M/s)'] = df['V0_(uM/s)'] * 10**(-6)
display(df)
```

#### (b) Plot & estimate
Plot the initial velocities, $V_0$, as a function of substrate concentrations, $[S]$. 
Estimate $K_M$ and $V_\mathrm{max}$ from this plot. 

```{python}
#| exercise: true
#| eval: false

fig, ax = plt.subplots()

## Your task: Plot '[S]_(M)' vs 'V0_(M/s)'.
... # Your code here. 

## Sets x and y-axis labels:
ax.set_xlabel('[S] (M)')
ax.set_ylabel('V0 (M/s)')

## EXTRA: Sets the y-axis limits.
ax.set_ylim(0, df['V0_(M/s)'].max()*1.2)
```

```{python}
#| solution: true

fig, ax = plt.subplots()

## Your task: Plot '[S]_(M)' vs 'V0_(M/s)'.
ax.plot(df['[S]_(M)'], df['V0_(M/s)'], 'o')

## Sets x and y-axis labels:
ax.set_xlabel('[S] (M)')
ax.set_ylabel('V0 (M/s)')

## EXTRA: Sets the y-axis limits.
ax.set_ylim(0, df['V0_(M/s)'].max()*1.2)
```

Put your estimate of $K_M$ and $V_\text{max}$ in the cell below:

```{python}
#| exercise: true
#| eval: false

## Task: Put your estimate of the two parameters.
Vmax_estimate = ...
K_M_estimate = ...
```

```{python}
#| solution: true

## Task: Put your estimate of the two parameters.
Vmax_estimate = 0.0005
K_M_estimate = 0.005
```

#### (c) Fit

Now we want to fit using the Michaelis-Menten equation, as per usual when the
task is fitting we have to define the function we are fitting with

```{python}
#| exercise: true
#| eval: false
def michaelis_menten(S, K_M, Vmax):
    ## Your task: Implement the Michaelis-Menten equation.
    ## Be careful with parentheses.
    result = ...
    return result
```

```{python}
#| solution: true
def michaelis_menten(S, K_M, Vmax):
    ## Your task: Implement the Michaelis-Menten equation.
    ## Be careful with parentheses.
    result = (Vmax * S) / (K_M + S)
    return result
```

And then we can follow our usual procedure to make the fit

```{python}
#| exercise: true
#| eval: false

initial_guess = [K_M_estimate, Vmax_estimate]

## Your task: Use curve_fit 
fitted_parameters, trash = ...

## Extracts and prints
K_M_fit, Vmax_fit = fitted_parameters
print(Vmax_fit)
print(K_M_fit)
```

```{python}
#| solution: true

initial_guess = [K_M_estimate, Vmax_estimate]

## Your task: Use curve_fit
fitted_parameters, trash = curve_fit(michaelis_menten, df['[S]_(M)'], df['V0_(M/s)'], initial_guess)

## Extracts and prints
K_M_fit, Vmax_fit = fitted_parameters
print(Vmax_fit)
print(K_M_fit)
```

How do these values compare to your estimate? 

#### (d) Plot fit & data

Plot the fit alongside the data. 

```{python}
#| exercise: true
#| eval: false

## Your task: Evaluate the fit
S_smooth = np.linspace(0, 0.055)
V0_fit = ...

## Creates the figure
fig, ax = plt.subplots()

## Your task: Make plot of the fit.
...

## This plot the data and sets the options as before.
ax.plot(df['[S]_(M)'], df['V0_(M/s)'], 'o')

## Sets x and y-axis labels:
ax.set_xlabel('[S] (M)')
ax.set_ylabel('V0 (M/s)')

## EXTRA: Sets the y-axis limits.
ax.set_ylim(0, df['V0_(M/s)'].max()*1.2)
```

```{python}
#| solution: true

## Your task: Evaluate the fit
S_smooth = np.linspace(0, 0.055)
V0_fit = michaelis_menten(S_smooth, K_M_fit, Vmax_estimate)

## Your task: Make the plot 
fig, ax = plt.subplots()

## Your task: Make plot of the fit.
ax.plot(S_smooth, V0_fit)

## This plot the data and sets the options as before.
ax.plot(df['[S]_(M)'], df['V0_(M/s)'], 'o')

## Sets x and y-axis labels:
ax.set_xlabel('[S] (M)')
ax.set_ylabel('V0 (M/s)')

## EXTRA: Sets the y-axis limits.
ax.set_ylim(0, df['V0_(M/s)'].max()*1.2)
```

#### (e) $k_{cat}$

The enzyme concentration was $100 \ \mathrm{nM}$ use that and your fit to determine $k_{cat}$.

```{python}
#| exercise: true
#| eval: false

## Your task: Set the enzyme concentration in proper units.
enzyme_concentration = ...

## Your task calculate kcat
kcat = ...
print(kcat)
```

```{python}
#| solution: true

## Your task: Set the enzyme concentration in proper units.
enzyme_concentration = 100 * 10**(-9) # nM

## Your task calculate kcat
kcat = Vmax_fit / enzyme_concentration # (nM/s) / nM  -> 1/s
print(kcat)
```

