## Competition in ligand binding

Below is given the general expression for saturation of a binding site by one of the ligands, $L$, when two ligands
$L$ and $C$ are competing for binding to the same site on a protein. Assume that $[P_T] = 10^{-9}$ $\mathrm{M}$.

$$
\theta_L = \frac{[PL]}{[P_T]} = \frac{1}{\frac{K_D}{[L]}\left(1 + \frac{[C]}{K_C}\right) + 1}
$$

Consider these four situations 

| #      | $[L_T]$                  | $[C_T]$                  | $K_D$                    | $K_C$                    |
|--------|--------------------------|--------------------------|--------------------------|--------------------------|
| 1      | $1·10^{-3}$ $\mathrm{M}$ | $0$                      | $1·10^{-5}$ $\mathrm{M}$ | $1·10^{-6}$ $\mathrm{M}$ |
| 2      | $1·10^{-3}$ $\mathrm{M}$ | $1·10^{-2}$ $\mathrm{M}$ | $1·10^{-5}$ $\mathrm{M}$ | $1·10^{-6}$ $\mathrm{M}$ |
| 3      | $1·10^{-3}$ $\mathrm{M}$ | $1·10^{-3}$ $\mathrm{M}$ | $1·10^{-5}$ $\mathrm{M}$ | $1·10^{-5}$ $\mathrm{M}$ |
| 4      | $1·10^{-5}$ $\mathrm{M}$ | $1·10^{-6}$ $\mathrm{M}$ | $1·10^{-5}$ $\mathrm{M}$ | $1·10^{-6}$ $\mathrm{M}$ |

##### (a) Explain simplification

Explain how the fact that $[P_T]$ is much smaller than $[L_T]$ and $[C_T]$ simplifies the calculations using the above equation.

```{python}
#| solution: true
#| eval: false
"""
When P(total) is << L(total) and C(total), we can assume that L(total) =[L] and C(total) = [C].
"""
```

#### (b) Ligand degree of saturation

Calculate the degree of saturation of the protein with ligand $L$ in the four situations.

Start by writing a Python function that calculates the degree of saturation $\theta$.

```{python}
#| exercise: true
#| eval: false
def bound_fraction(L, C, Kd, Kc):    
    ## Your task: Write the equation for binding saturation. 
    ## Be careful with parentheses!
    theta = ... 
    return theta
```

```{python}
#| solution: true
def bound_fraction(L, C, Kd, Kc):
    ## Your task: Write the equation for binding saturation. 
    ## Be careful with parentheses!
    theta = 1 / ((Kd / L)*(1+(C/Kc))+1) 
    return theta
```

Then use that function to calculate $\theta_L$ for each situation.

```{python}
#| exercise: true
#| eval: false

## Your task: Calculate the degree of saturation for each set of parameters ##
theta_L_1 = bound_fraction(..., ..., ..., ...)
theta_L_2 = ...
theta_L_3 = ...
theta_L_4 = ...
print('Situation 1', theta_L_1)
print('Situation 2', theta_L_2)
print('Situation 3', theta_L_3)
print('Situation 4', theta_L_4)
```

```{python}
#| solution: true

## Your task: Calculate the degree of saturation for each set of parameters ##
theta_L_1 = bound_fraction(10**(-3), 0, 10**(-5), 10**(-18))
theta_L_2 = bound_fraction(10**(-3), 10**(-2), 10**(-5), 10**(-6))
theta_L_3 = bound_fraction(10**(-3), 10**(-3), 10**(-5), 10**(-5))
theta_L_4 = bound_fraction(10**(-5), 10**(-6), 10**(-5), 10**(-6))

## Prints the results so we can analyze them.
print('Situation 1', theta_L_1)
print('Situation 2', theta_L_2)
print('Situation 3', theta_L_3)
print('Situation 4', theta_L_4)
```

#### (c) Competitor degree of saturation

What is the degree of saturation with respect to the competitor $C$ in #1, #2, #3 and #4?

```{python}
#| exercise: true
#| eval: false
## Your task: Calculate the degree of saturation for each set of parameters ##
## Note: Now you are calculating it for the competitor!
theta_C_1 = ...
theta_C_2 = ...
theta_C_3 = ...
theta_C_4 = ...

## Prints the results so we can analyze them.
print('Situation 1', theta_C_1)
print('Situation 2', theta_C_2)
print('Situation 3', theta_C_3)
print('Situation 4', theta_C_4)
```

```{python}
#| solution: true
## Your task: Calculate the degree of saturation for each set of parameters ##
## Note: Now you are calculating it for the competitor!
theta_C_1 = 0 # [C] = 0
theta_C_2 = bound_fraction(10**(-2), 10**(-3), 10**(-6), 10**(-5))
theta_C_3 = bound_fraction(10**(-3), 10**(-3), 10**(-5), 10**(-5))
theta_C_4 = bound_fraction(10**(-6), 10**(-5), 10**(-6), 10**(-5))

## Prints the results so we can analyze them.
print('Situation 1', theta_C_1)
print('Situation 2', theta_C_2)
print('Situation 3', theta_C_3)
print('Situation 4', theta_C_4)
```

#### (d) Fraction of $[P_{\mathrm{free}}]$

What is the fraction of $[P_{\mathrm{free}}]$ in #1, #2, #3 and #4? 

::: {.callout-tip}

Consider how to express the fraction of $[P_{\mathrm{free}}]$ in terms of `theta_L_X` and `theta_C_X`. 

:::

```{python}
#| exercise: true
#| eval: false

## Your task: Calculate the P_free. 
## Hint: Do not use the function from before - figure out another way. 
theta_free_1 = ...
theta_free_2 = ...
theta_free_3 = ...
theta_free_4 = ...

## Prints the results so we can analyze them.
print('Situation 1', theta_free_1)
print('Situation 2', theta_free_2)
print('Situation 3', theta_free_3)
print('Situation 4', theta_free_4)
```

```{python}
#| solution: true
theta_free_1 = 1 - (theta_L_1 + theta_C_1)
theta_free_2 = 1 - (theta_L_2 + theta_C_2)
theta_free_3 = 1 - (theta_L_3 + theta_C_3)
theta_free_4 = 1 - (theta_L_4 + theta_C_4)

## Prints the results so we can analyze them.
print('Situation 1', theta_free_1)
print('Situation 2', theta_free_2)
print('Situation 3', theta_free_3)
print('Situation 4', theta_free_4)
```

#### (e) Qualitative analysis

Describe in your own words why these four competitive situations end up with 
their respective binding patterns. Consider the relative concentrations and 
affinities of ligands L and C.

```{python}
#| solution: true
#| eval: false
"""
1. The competitor concentration is zero, so only the ligand L binds. Affinity/concentration is such that nearly all proteins have an L-ligand bound.

2. The affinity and concentration of C is higher so it binds more and the ratio of affinity and concentration is high enough that nearly all proteins have a C-ligand bound. 

3. The affinity and concentration of L and C are equal and they both bind equally. Again, the affinities/concentrations are such that nearly all proteins have a ligand bound. 

4. K_D > K_C with the same factor as [L_T] > [C_T] so they bind equally but 
there are still free proteins as the concentrations are low relative to the affinities. 
"""
```
