## Determination of ΔH° for a reaction from the van’t Hoff plot.
```{python}
#| code-fold: true
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
import numpy as np
from fysisk_biokemi.widgets import DataUploader
from IPython.display import display 
```


The equilibrium constant for a reversible reaction going from $A$ to $B$ was measured as a function of temperature.
 
The data obtained is given in the Excel document `deter_delta_h_data.xlsx` - load the data with the widget 

```{python}
#| eval: false
uploader = DataUploader()
uploader.display()
```

Run the next cell **after** uploading the file

```{python}
#| eval: false
df = uploader.get_dataframe()
display(df)
```

```{python}
#| solution: true
from fysisk_biokemi.datasets import load_dataset
df = load_dataset('deter_delta_h') # Load from package for the solution so it doesn't require to interact.
display(df)
```

#### (a) Transform & plot the data

::: {.callout-tip}
In NumPy the `np.log` function calculates the natural logarithm that we often write as $\ln$ and `np.log10` calculates the 
base 10 logarithm. 
:::

Add new columns to the `DataFrame` containing $\ln(K_{eq})$ and $1/T$ and make a plot 
with $1/T$ on the x-axis and $\ln(K_{eq})$ on the y-axis.

```{python}
#| exercise: true
#| eval: false 

## Your task: Add a column containing 1/T and one containing ln(Keq) ##
df['1/T'] = ...
df['ln_Keq'] = ...
```

```{python}
#| solution: true

## Your task: Add a column containing 1/T and one containing ln(Keq) ##
df['1/T'] = 1/df['T_(K)']
df['ln(Keq)'] = np.log(df['Keq'])
```

Now you can make the plot in the cell below

```{python}
#| exercise: true
#| eval: false
fig, ax = plt.subplots()

## Your task: Make a plot of 1/T vs ln(Keq)
...

## EXTRA: Customization you don't need to edit or understand this
## It adds axis labels to the plot you made.
ax.set_xlabel(r'1/T [K]')
ax.set_ylabel(r'$\ln(K_{eq})$');
```

```{python}
#| solution: true
#| fig-align: center
fig, ax = plt.subplots()

## Your task: Make a plot of 1/T vs ln(Keq)
ax.plot(df['1/T'], df['ln(Keq)'], 'o')

## EXTRA: Customization you don't need to edit or understand this
## It adds axis labels to the plot you made.
ax.set_xlabel(r'1/T [K]')
ax.set_ylabel(r'$\ln(K_{eq})$');
```

#### (b) Fit trendline

Make a linear trendline by fitting a linear function to the data. 

Start by defining a linear function

```{python}
#| exercise: true
#| eval: false
def vant_hoff(T, a, b):
    ## Your task: Implement a linear function
    result = ...
    return result
```

```{python}
#| solution: true
def vant_hoff(T, a, b):
    ## Your task: Implement a linear function
    result = a * T + b
    return result
```

Now we can use regression to find the parameters 

```{python}
#| exercise: true
#| eval: false

## Your task: Make a fit with curve_fit to find the parameters ##
fitted_parameters, trash = ...
a_fit, b_fit = fitted_parameters

# Print
print(a_fit)
print(b_fit)
```

```{python}
#| solution: true

## Your task: Make a fit with curve_fit to find the parameters ##
fitted_parameters, trash = curve_fit(vant_hoff, df['1/T'], df['ln(Keq)'])
a_fit, b_fit = fitted_parameters

## Print ##
print(a_fit)
print(b_fit)
```

Then make a plot with the trendline added 

```{python}
#| exercise: true
#| eval: false
fig, ax = plt.subplots()

## Your task: Choose points to evaluate the fit
## Look at the x-axis above and estimate a value for the minimum and maximum. 
## Then calculate the fit at those points
max_x = ...
min_x = ...
T_trend = np.array([min_x, max_x]) # Select or make some appropriate points for the plotting evaluating the trendline.
y_fit = vant_hoff(T_trend, ..., ...)

## Your task: Plot the fit
...

## Plots the data
ax.plot(df['1/T'], df['ln(Keq)'], 'o')

## EXTRA: You do not need to edit or understand this.
## It adds axis labels to the plot you made.
ax.set_xlabel('1/T [K]')
ax.set_ylabel(r'$\ln(K_{eq})$');
```

```{python}
#| fig-align: center
#| solution: true
fig, ax = plt.subplots()

## Your task: Choose points to evaluate the fit
## Look at the x-axis above and estimate a value for the minimum and maximum. 
## Then calculate the fit at those points
max_x = 0.0032
min_x = 0.0036
T_trend = np.array([min_x, max_x])
y_fit = vant_hoff(T_trend, a_fit, b_fit)

## Your task: Plot the fit
ax.plot(T_trend, y_fit)

## Plots the data
ax.plot(df['1/T'], df['ln(Keq)'], 'o')

## EXTRA: You do not need to edit or understand this.
## It adds axis labels to the plot you made.
ax.set_xlabel('1/T [K]')
ax.set_ylabel(r'$\ln(K_{eq})$');
```

#### (c) Reaction type

Calculate the reaction enthalpy and entropy, at $T = 298 \ \mathrm{K}$, assuming that $R = 8.314472 \times 10^{-3} \ \frac{\mathrm{kJ}}{\mathrm{mol}\cdot\mathrm{K}}$. Is the reaction endo- or exothermic?

```{python}
#| solution: true

## Your task: Set known values and add units as comments e.g. # kJ/(mol K) ##
R = 8.314472 * 10**(-3) # Unit: # kJ/(mol K)
T = 298 # Unit: K 


## Your task: Calculate ΔH and ΔS ##
## Consider the units!
dH = -R * a_fit # kJ/mol
dS = R * b_fit # kJ/(mol K)

print(dH)
print(dS)
```

```{python}
#| exercise: true
#| eval: false

## Your task: Set known values and add units as comments e.g. # kJ/(mol K) ##
R = ... 
T = ...

## Your task: Calculate ΔH and ΔS ##
## Consider the units!
dH = ...
dS = ...

print(dH)
print(dS)
```

::: {.callout-tip}
The units of a slope is the units of the y-axis dvided by the units of the x-axis. 

In the van't Hoff plot the y-axis is unitless and the x-axis is in 1/K.
::: 



#### (d) Free energy change

Calculate the free energy change, $\Delta G^\circ$, at $T = 298 \ \mathrm{K}$, assuming that $R = 8.314472 \times 10^{-3} \ \frac{\mathrm{kJ}}{\mathrm{mol}\cdot\mathrm{K}}$

```{python}
#| exercise: true
#| eval: false

## Your task: Calculate ΔG
dG = ...

print(dG)
```

```{python}
#| solution: true

## Your task: Calculate ΔG
dG = dH - T * dS

print(dG)
```