## Dialysis experiment 

```{python}
#| code-fold: true
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
pd.set_option('display.max_rows', 6)
```

A dialysis experiment was set up where equal amounts of a protein were separately dialyzing against buffers containing different concentrations of a ligand – each measurement was done in triplicate. The average number of ligands bound per protein molecule, $\bar{n}$ were obtained from these experiments. The corresponding concentrations of free ligand and values are given in dataset `dialys-exper.xlsx`. 

#### (a)    Load the dataset

```{python}
#| eval: false
from fysisk_biokemi.widgets import DataUploader
from IPython.display import display 
uploader = DataUploader()
uploader.display()
```

Run the next cell **after** uploading the file

```{python}
#| eval: false
df = uploader.get_dataframe()
display(df)
```

```{python}
#| solution: true
from IPython.display import display 
from fysisk_biokemi.datasets import load_dataset
df = load_dataset('dialysis_experiment') # Load from package for the solution so it doesn't require to interact.
display(df)
```

#### (b) Explain calculation of $\bar{n}$

Explain how the values of $\bar{n}$ is calculated when knowing the concentrations of ligand inside and outside the dialysis bag, as well as the total concentration of the protein, [$\text{P}_{\text{tot}}$].

```{python}
#| solution: true
#| echo: false
from IPython.display import Markdown
answer="""
:::{.callout-note}
## Calculation of $\\bar{n}$

The concentration of free ligand [L] is the same inside and outside the dialysis
bag at equilibrium. Outside there is no protein, so only free ligand $L_{outside} = [L]$

The total concentration of ligand inside the dialysis bag is thus the combination 
of free and bound ligand $L_{inside} = [L] + [PL]$. [PL] can thus be calculated as:

$$[PL] = [L_{inside}] - [L_{outside}]$$

This can be combined with $[P_{tot}]$ to give $\\bar{n}$:

$$\\bar{n} = \\frac{[L_{inside}] - [L_{outside}]}{[P_{tot}]}$$
:::
"""
display(Markdown(answer))
```
#### (c) Molar concentrations

Convert the concentrations of free ligand to SI-units given in M, add it as a row to the `DataFrame`. 

```{python}
#| exercise: true
#| eval: false

## Your task: Convert the concentration to SI units (from uM to M). 
## The column containing the data in uM can be indexed with: df['Free_ligand_(uM)']
df['Free_ligand_(M)'] = ...
display(df)
```

```{python}
#| solution: true
df['Free_ligand_(M)'] = df['Free_ligand_(uM)'] * 10**(-6)
display(df)
```


#### (d) Plot the data

```{python}
#| exercise: true
#| eval: false
fig, ax = plt.subplots()

## Your task: Plot the raw data 
## With the ligand concentration df['Free_ligand_(M)'] on the x-axis
## And with n-bar df['n_bar'] on the y-axis.
ax.plot(..., ..., 'o')
```

```{python}
#| solution: true
fig, ax = plt.subplots()

## Your task: Plot the raw data 
## With the ligand concentration df['Free_ligand_(M)'] on the x-axis
## And with n-bar df['n_bar'] on the y-axis.
ax.plot(df['Free_ligand_(M)'], df['n_bar'], 'o')

## EXTRAS: You do not need to understand this ## 
## This adds customization ##
ax.set_xlabel('Free ligand [L] (M)', fontsize=16)
ax.set_ylabel(r'$\bar{n}$', fontsize=16);
```

#### (e) Prepare for fitting

Now we want to fit the data to extract $K_D$ and $n$, by using the equation

$$
\bar{n}([L_{\text{free}}]) = N \frac{[L_{\text{free}}]}{K_D + [L_{\text{free}}]}
$$

To do so we need to implmenet it as a Python function 

```{python}
#| exercise: true
#| eval: false
def nbar(L, N, K_D):
    ## Your task: Calculate n-bar using the equation from above.
    result = ... 
    return result

## This calculates the function and prints for two different sets of values ## 
print(nbar(1, 1, 1)) # Should give 1/2
print(nbar(21, 47, 2.5)) # Should give 42
```

```{python}
#| solution: true
def nbar(L, N, K_D):
    return N * L / (K_D + L)

## This calculates the function and prints for two different sets of values ## 
print(nbar(1, 1, 1)) # Should give 1/2
print(nbar(21, 47, 2.5)) # Should give 42
```

#### (f) Actually fitting

Finish the code to perform the fitting in the cell below.

```{python}
#| exercise: true
#| eval: false
from scipy.optimize import curve_fit

# Choose the variables from the dataframe
x = df['Free_ligand_(M)']
y = df['n_bar']

## Your task: Make initial guesses for the two parameters ## 
K_D_guess = ... # Your initial guess for K_D 
N_guess = ... # Your initial guess for N.
initial_guess = [K_D_guess, N_guess]

## Your task: Give the four arguments in the correct order to make calculate ##
## the fitted parameters ##
fitted_parameters, trash = curve_fit(..., ..., ..., ...) 

# Print the parameters
N_fit, K_D_fit = fitted_parameters
print(fitted_parameters)
print(N_fit)
print(K_D_fit)
```

```{python}
#| solution: true
from scipy.optimize import curve_fit

# Choose the variables from the dataframe
x = df['Free_ligand_(M)']
y = df['n_bar']

## Your task: Make initial guesses for the two parameters ## 
K_D_guess = 10**(-5)
N_guess = 1
initial_guess = [K_D_guess, N_guess]

## Your task: Give the four arguments in the correct order to make calculate ##
## the fitted parameters ##
fitted_parameters, pcov = curve_fit(nbar, x, y, initial_guess)

# Print the parameters
N_fit, K_D_fit = fitted_parameters
print(fitted_parameters)
print(N_fit)
print(K_D_fit)
```

Are the parameters you find reasonable? How can you tell if they are reasonable by 
looking at the plot you made earlier? 

#### (g) Plot with fit

When we have the fitted parameters we can calculate and plot the function. To do so 
we make an array of values for the independent variable and use our function to 
calculate the dependent variable

```{python}
#| exercise: true
#| eval: false
## This makes 50 equally spaced points ##
L_smooth = np.linspace(0, x.max()*1.2, 50) 

## Your task: Calculate the fitted function using the found parameters and L_smooth
nbar_calc = ...
```

```{python}
#| solution: true
## This makes 50 equally spaced points ##
L_smooth = np.linspace(0, x.max()*1.2, 50) 

## Your task: Calculate the fitted function using the found parameters and L_smooth
nbar_calc = nbar(L_smooth, N_fit, K_D_fit)
```

Now that we calculated the dependent variable we can plot the fit along with the data. 

```{python}
#| exercise: true
#| eval: false
fig, ax = plt.subplots()

## Your task: Plot the fitted function ##
ax.plot(..., ...)

## Plots the data ## 
ax.plot(df['Free_ligand_(M)'], df['n_bar'], 'o')
```

```{python}
#| solution: true
fig, ax = plt.subplots()

## Your task: Plot the fitted function ##
ax.plot(L_smooth, nbar_calc)

## Plots the data ## 
ax.plot(df['Free_ligand_(M)'], df['n_bar'], 'o')

## EXTRA: You do not need to understand this ## 
## This customizes the plot ## 
## It also adds lines indicating the values of n and K_D found ## 
ax.axhline(N_fit, color='red', label=r'$N$')
ax.axvline(K_D_fit, color='green', label=r'$K_D$')
ax.set_xlabel('Free ligand [L] (M)', fontsize=16)
ax.set_ylabel(r'$\bar{n}$', fontsize=16)
ax.legend(fontsize=16)
```

