## Difference between $Q$ and $K_{eq}$

```{python}
#| code-fold: true
import matplotlib.pyplot as plt
import pandas as pd
from fysisk_biokemi.widgets import DataUploader
from IPython.display import display 
pd.set_option('display.max_rows', 6)
```

Consider the reaction:

$$
A \rightleftarrows B
$$

The time course of the reaction was followed monitoring formation of the product $B$. The starting concentration of $A$ was 50 µM, and as you will learn later in the course, the reversible reaction going from $A$ to $B$ follows first order kinetics. 

#### (a) Load & convert

The data is contained in the `diff_q_keq_data.xlsx` file.

```{python}
#| eval: false
uploader = DataUploader()
uploader.display()
```

Run the next cell **after** uploading the file

```{python}
#| eval: false
df = uploader.get_dataframe()
display(df)
```

```{python}
#| solution: true
from fysisk_biokemi.datasets import load_dataset
df = load_dataset('diff_q_keq') # Load from package for the solution so it doesn't require to interact.
display(df)
```

Convert the measured concentrations of $B$, $[B]$, to concentrations in the SI-unit $\mathrm{M} \ (\mathrm{mol/L})$. Repeat for the starting concentration of $A$, $[A_0]$.

```{python}
#| exercise: true
#| eval: false

## Your task: Convert the concentration of B to M and set in new column ##
df['[B]_(M)'] = ...

## Your task: Set the initial concentration of A, in the variable A0.
## Remember to convert to M.
A0 = ...
```

```{python}
#| solution: true

## Your task: Convert the concentration of B to M and set in new column ##
df['[B]_(M)'] = df['[B]_(uM)'] * 10**(-6) # Unit: M

## Your task: Set the initial concentration of A, in the variable A0.
## Remember to convert to M.
A0 = 50 * 10**(-6) # Unit: M 
```


#### (b) Law of mass balance

Use the laws of mass balance to calculate $[A]$ as a function of time in the unit $\mathrm{M}$, 
add it as a column to the `DataFrame` 

```{python}
#| exercise: true
#| eval: false

# Your task: Calculate the concentration of A for each time-point
## Add it as a column to the dataframe called '[A]_(M)'.
... # Your code here.
```

```{python}
#| solution: true
df['[A]_(M)'] = A0 - df['[B]_(M)']
```

Make a plot of the time vs. the concentration of $A$ and of time versus the concentration of $B$.

```{python}
#| exercise: true
#| eval: false

fig, ax = plt.subplots()
## Your task: Plot time vs. concentrations. ##
ax.plot(..., ..., label='[A]') # Time vs. concentration of A
ax.plot(..., ..., label='[B]') # Time vs. concentration of B

## This shows the labels. ##
ax.legend()
```

```{python}
#| solution: true
#| fig-align: center

fig, ax = plt.subplots()
## Your task: Plot time vs. concentrations.
ax.plot(df['Time_(min)'], df['[A]_(M)'], label='[A]') # Time vs. concentration of A
ax.plot(df['Time_(min)'], df['[B]_(M)'], label='[B]') # Time vs. concentration of B

## This shows the labels.
ax.legend()

## EXTRA: You do not need to understand this: 
ax.set_xlabel('Time [min]')
ax.set_ylabel('Concentrations [M]')
```


#### (c) Mass action ratio

Calculate and plot the mass action ratio $Q$ as a function of time.

```{python}
#| exercise: true
#| eval: false

## Your task: Calculate the mass action ratio
Q = ... # calculate Q 
```

```{python}
#| solution: true
#| fig-align: center

## Your task: Calculate the mass action ratio
Q = df['[B]_(M)'] / df['[A]_(M)']
```

Now plot the mass action ratio versus time.

```{python}
#| exercise: true
#| eval: false
fig, ax = plt.subplots()

## Your task: Make a plot of the axis from the dataframe df['Time_(min)'] vs Q
...
```

```{python}
#| solution: true
#| fig-align: center
fig, ax = plt.subplots()

## Your task: Make a plot of the axis from the dataframe df['Time_(min)'] vs Q
ax.plot(df['Time_(min)'], Q)

## EXTRA: You do not need to understand this
## Adds customization.
ax.set_xlabel('Time (min)')
ax.set_ylabel('Mass action ratio $Q$')
```

#### (d) $Q$ vs $K_{eq}$

What is the difference between $Q$ and $K_{eq}$? 

```{python}
#| solution: true
#| eval: false
"""
Q is the mass action ratio at any time throughout the reaction. Keq is the mass 
action ratio at equilibrium only, and tells about the energetic favorisation of 
one direction over the other.
"""
```

#### (e) Favoured compound

Which of the two compounds $A$ and $B$ is favored at equilibrium? (Favored: highest concentration)

```{python}
#| solution: true
#| eval: false
"""
When the reaction reaches close to equilibrium, more B is present as compared to A, telling that B is favored. 
Keq > 1 --> B is favored
"""
```

#### (f) Equilibrium constant

What is the equilibrium constant of this reaction?

```{python}
#| solution: true
"""
Can also just read the concentrations values at eq from the graph and calculate K_eq from those. 
But it can of course also just be calculated.
"""
K_eq = df['[B]_(M)'][35] / df['[A]_(M)'][35]
print(K_eq)
```

 
