## Qualitative description of Michaelis-Menten kinetics 

```{python}
#| code-fold: true
import plotly
import fysisk_biokemi.widgets as fbw
from fysisk_biokemi.widgets.utils import enable_custom_widget_colab, disable_custom_widget_colab
from IPython.display import display, HTML
enable_custom_widget_colab()
```

```{python}
#| eval: false
fbw.michaelis_menten_demo()
```

Use the widget created by the cell above to answer the following the questions.

#### (a) Change $K_M$

Setting $V_\mathrm{max} = 400$ and $[E]_\mathrm{tot} = 0.0005$, change $K_M$ from 0.5 to 5 to 10 to 50. Describe the change in curve appearance and explain it using the Michaelis-Menten (MM) equation.

:::::: {.cell .markdown}

::::::

#### (b) Meaning of $K_M$

What is the biochemical meaning of $K_M$?

:::::: {.cell .markdown}

::::::

#### (c) Change $V_\mathrm{max}$ and $[E]_\mathrm{tot}$

Now set $[E]_\mathrm{tot} = 0.0005$, and $K_M = 5$. Change $V_\mathrm{max}$ step-wise from 40 to 900. Describe the changes you observe and how they relate to the MM equation. 

After this, repeat the procedure for $[E]_\mathrm{tot} increasing it 10-fold.  

:::::: {.cell .markdown}

::::::

#### (d) Substrate concentrations way below $K_M

Next, we will explore the regime where [S]>>$K_M. Initially, set $K_M = 10$ and zoom in on the regime from 0 - 1 on the X-axis. What does the MM equation look like in this regime? Use the MM equation and a simplifying assumption to show how this ccurs. 

Next, increase $K_M five-fold and try to change $V_\mathrm{max}$ som the curve appearance is unchanged (beware of the autoscaling Y-axis).

Imagine an experiment conducted using only [S] values from this range. How would this affect how well you could determine the MM parameters? 

:::::: {.cell .markdown}

::::::

#### (f) Training estimation skills.

Train your estimation skills using the widget below.

```{python}
#| eval: false
fbw.michealis_menten_guess()
```
