## The pH effect on an active site histidine residue

Assume that a compound R can react with the unprotonated form of Histidine, 
$\text{His}$, to form a covalent reaction product, $\text{P}$:
$$
\text{His} + \text{R} \rightarrow \text{P}
$$

The protonated form of Histidine, $\text{HisH}^+$, is in equilibrium with $\text{His}$:

$$
\text{HisH}^+ \rightleftharpoons \text{His} + \text{H}^+
$$

The pKa value for this acid-base equilibrium is 6.0. Further assume that the total
concentration of Histidine, is

$$
[\text{HisH}^+] + [\text{His}] = 10^{-3} \ \text{M}
$$

#### (a) Percentage unprotonated

What percentage of Histidine is unprotonated at pH 6.0. What do you notice about the relationship between pH and pKa in this case? (You should not need to do any arithemtic or algebra to answer this exercise.)

```{python}
#| exercise: true
#| eval: false 

## Your task: What percentage is unprotonated? 
percentage_unprotonated = ...
```

```{python}
#| solution: true

## Your task: What percentage is unprotonated? 
percentage_unprotonated = 50
```

```{python}
#| solution: true
#| output: asis
#| echo: false
answer=r"""
::: {.callout-important}

## Answer

Because $\text{pH} = \text{pKa}$ the percentage of unprotonated is 50%, so there 
is no need to do a direct calculation in this case.

:::
"""
print(answer)
```


#### (b) Concentration 

Determine $[\text{His}]$ at pH 6

```{python}
#| exercise: true
#| eval: false

## Your task: Assign known value and calculate [His]
total_conc = ...
his_conc = ...
print(his_conc)
```

```{python}
#| solution: true

## Your task: Assign known value and calculate [His]
total_conc = 10**(-3)
his_conc = total_conc * percentage_unprotonated / 100 # Unit: M
print(his_conc)

# Or directly 
his_conc = 0.5 * 10**(-3) # Unit: M
print(his_conc)
```

#### (c) Reaction order

The reaction equation for the reaction between  $\text{His}$ and $\text{R}$ is 

$$
v = - \frac{d[\text{His}]}{dt} = k \cdot [\text{His}] \cdot [\text{R}]
$$

What's the reaction order? 

```{python}
#| solution: true
#| output: asis
#| echo: false
answer=r"""
::: {.callout-important}

## Answer
Bimolecular so we expect second order reaction.

:::
"""
print(answer)
```


#### (d) High concentrations

If $[\text{R}]$ is much higher than $[\text{His}]$, what can then be concluded regarding the order of the reaction? 

```{python}
#| solution: true
#| output: asis
#| echo: false
answer=r"""
::: {.callout-important}

## Answer
$[R]$ will remain roughly constant - we are thus in the regime of a pseudo first order reaction

:::
"""
print(answer)
```

#### (e) New rate constant

Show how a new rate constant, $k'$, can be defined in these conditions. How does $k'$ depend on $\text{R}$?

```{python}
#| solution: true
#| output: asis
#| echo: false
answer=r"""
::: {.callout-important}

## Answer
$v = k \cdot [\text{His}] \cdot [\text{R}]$

$k^{\prime} = k[\text{R}]$

$v = k^{\prime}[\text{His}]$


Then $k^{\prime}$ is linearly proportional with $[\text{R}]$.

:::
"""
print(answer)
```


#### (f) SI Units

At pH 6.0 the reaction rate $v = 1 \ \text{mM}\cdot \text{s}^{-1}$.

Convert the reaction rate to SI-units given in $\text{M}\cdot \text{s}^{-1}$.

```{python}
#| exercise: true
#| eval: false

# Your task: Calculate v in SI units M / s
reaction_rate = ...
print(reaction_rate)
```

```{python}
#| solution: true

# Your task: Calculate v in SI units M / s
reaction_rate = 1 * 10**(-3) # Units: M / s
print(reaction_rate)
```

#### (g) Calculate the rate constant 

Use the concentration of $[\text{His}]$ at pH 6 calculated in question (b), the reaction rate from (f) and constant $[\text{R}] = 0.2 \ \text{M}$ to calculate the rate constant $k$. 

```{python}
#| eval: false
#| exercise: true

## Your task: Set known value and calculate k ##
## Hint: You should use the his_conc and reaction_rate variables ##
R_conc = ...
k = ...
print(k)
```

```{python}
#| solution: true

## Your task: Set known value and calculate k ##
## Hint: You can use the his_conc variable ##
R_conc = 0.2
k = reaction_rate / (R_conc * his_conc)
print(k)
```
