## Tryptophan absorption and fluorescence

```{python}
from fysisk_biokemi.datasets import load_dataset
from IPython.display import display
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', 6)
```

You investigate a protein that neither contains tyrosine nor cysteine residues. A 37 µM solution gives an absorbance of 0.41 at 280nm at a light path of 1 cm.

#### (a) Number of residues

How many tryptophan residues does the protein contain?

```{python}
#| exercise: true
#| eval: false
...
```

#### (b) Concentration

You would like to conduct a protein stability experiment at an absorbance of 0,8 (path length 1cm). What concentration should you use?

```{python}
#| exercise: true
#| eval: false
...
```

#### (c) Plot the spectra

The cell below loads extinction and emission spectra for tryptophan in aqueous buffer. (The data files are 
`trypt-absor-fluor-emission.xlsx` and `trypt-absor-fluor-extinction.xlsx`)

```{python}
df_emission = load_dataset('week47_1_emi')
df_extinction = load_dataset('week47_1_ext')
display(df_emission)
display(df_extinction)
```

Make plot showing the two spectra 

```{python}
#| exercise: true
#| eval: false
fig, axes = plt.subplots(1, 2, figsize=(7, 3), layout='constrained')

# Emission 
ax = axes[0]
ax.set_title('Emission')

# Replace ... with your code.
ax.plot(..., ..., label='Emission', color='C0')

ax.set_ylabel('Emission')
ax.set_xlabel('Wavelength [nm]')

# Extinction
ax = axes[1]
ax.set_title('Extinction')

# Replace ... to plot the extinction spectrum
...

# Customization
ax.set_ylabel('Extinction')
ax.set_xlabel('Wavelength [nm]')
plt.show()
```

```{python}
#| solution: true
#| fig-align: center
fig, axes = plt.subplots(1, 2, figsize=(7, 3), layout='constrained')

# Emission 
ax = axes[0]
ax.set_title('Emission')
ax.plot(df_emission['wavelength_(nm)'], df_emission['emission_(AU)'], label='Emission', color='C0')
ax.set_ylabel('Emission')
ax.set_xlabel('Wavelength [nm]')

# Extinction
ax = axes[1]
ax.set_title('Extinction')
ax.plot(df_extinction['wavelength_(nm)'], df_extinction['molar_extinction_(cm-1/M)'], label='Extinction', color='C1')

# Customization
ax.set_ylabel('Extinction')
ax.set_xlabel('Wavelength [nm]')
plt.show()
```

#### (d) Stokes shift

From the plot estimate the Stokes shift

```{python}
#| exercise: true
#| eval: false
estimated_stokes_shift = ...
```

```{python}
#| solution: true
estimated_stokes_shift = 30
```

Compare your estimated Stokes shift to the output of the cell below that computes 
the stokes shift. 

```{python}
#| exercise: true
#| eval: false
max_index = np.argmax(df_emission['emission_(AU)'])
emission_wavelength_max = df_emission['wavelength_(nm)'][max_index]

max_index = np.argmax(df_extinction['molar_extinction_(cm-1/M)'])
extinction_wavelength_max = df_extinction['wavelength_(nm)'][max_index]

stokes_shift = emission_wavelength_max - extinction_wavelength_max

print(f"{emission_wavelength_max = :.1f} nm")
print(f"{extinction_wavelength_max = :.1f} nm")
print(f"{stokes_shift = :.1f} nm")
print(f"{estimated_stokes_shift = :.1f} nm")
```

```{python}
#| solution: true
max_index = np.argmax(df_emission['emission_(AU)'])
emission_wavelength_max = df_emission['wavelength_(nm)'][max_index]

max_index = np.argmax(df_extinction['molar_extinction_(cm-1/M)'])
extinction_wavelength_max = df_extinction['wavelength_(nm)'][max_index]

stokes_shift = emission_wavelength_max - extinction_wavelength_max

print(f"{emission_wavelength_max = :.1f} nm")
print(f"{extinction_wavelength_max = :.1f} nm")
print(f"{stokes_shift = :.1f} nm")
print(f"{estimated_stokes_shift = :.1f} nm")
```

#### (e) pH and how it changes pHroperties.

Next, you compare the fluorescence emission spectra for your protein at pH 7 and at pH 2. You can find the data in the files `trypt-absor-fluor-ph2.xlsx` and `trypt-absor-fluor-ph7.xlsx` - the cell below also loads these datasets. 

::: {callout-tip}

The datasets are loaded in a different way than you've seen before - as help to you 
as this exercise deals with multiple datasets. The datasets could also be loaded with the 
widget you've seen before

::: 

```{python}
df_ph2 = load_dataset('week47_1_ph2')
df_ph7 = load_dataset('week47_1_ph7')
display(df_ph2, df_ph2)
```

Make a plot comparing the two emission spectra. Which resembles the spectrum of tryptophan in water most?

```{python}
#| fig-align: center
#| exercise: true
#| eval: false
fig, ax = plt.subplots()

ax.plot(..., ..., label='pH = 2') # Replace to plot at pH = 2
... # Replace to plot at pH = 7

ax.set_xlabel('Wavelength [nm]')
ax.set_ylabel('Flouresence [AU]')
ax.legend()
plt.show()
```

```{python}
#| fig-align: center
#| solution: true
fig, ax = plt.subplots()

ax.plot(df_ph2['Wavelength(nm)'], df_ph2['Fluo_Int'], label='pH = 2')
ax.plot(df_ph7['Wavelength(nm)'], df_ph7['Fluo_Int'], label='pH = 7')

ax.set_xlabel('Wavelength [nm]')
ax.set_ylabel('Flouresence [AU]')
ax.legend()
plt.show()
```

#### (f) for explain.

Explain why the same protein gives such different spectra at pH 2 and pH 7. 
 
```{python}
#| solution: true
#| eval: false
"""
The protein unfolds at acidic pH. Therefore the Trp residues are exposed to water 
at pH 2, but buried in the hydrophobic core (and thus blue-shifted) at pH 7
"""
```