---
title: "The pH effect on an active site histidine residue"
categories: ['plotting', 'calculaton']
topics: []
datasets: ['week48_7_reaction_order_activation.csv']
---


## The pH effect on an active site histidine residue

Assume that a compound R can react with the unprotonated form of Histidine, 
$\text{His}$, to form a covalent reaction product, $\text{P}$:
$$
\text{His} + \text{R} \rightarrow \text{P}
$$

The protonated form of Histidine, $\text{HisH}^+$, is in equilibrium with $\text{His}$:

$$
\text{HisH}^+ \rightleftharpoons \text{His} + \text{H}^+
$$

The pKa value for this acid-base equilibrium is 6.0. Further assume that the total
concentration of Histidine, is

$$
[\text{HisH}^+] + [\text{His}] = 10^{-3} \ \text{M}
$$

#### (a) Percentage unprotonated

Using the Henderson-Hasselbach equation, calculate the percentage of unprotonated 
Histidine, $\text{His}$, at pH 6.0. 

```{python}
#| exercise: true
#| eval: false 
pKa = ...
pH = ...

... # Possible intermediate calculation, otherwise delete this line.

percentage_unprotonated = ...
print(f"{percentage_unprotonated = } %")
```

```{python}
#| solution: true
pKa = 6.0
pH = 6.0
ratio = 10 ** (pH - pKa)
percentage_unprotonated = 1 / (1 + ratio) * 100
print(f"{percentage_unprotonated = } %")
```

#### (b) Concentration 

Calculate $[\text{His}]$ at pH 6

```{python}
#| exercise: true
#| eval: false
total_conc = ...
his_conc = ...
print(f"{his_conc = } M")
```

```{python}
#| solution: true
total_conc = 10**(-3)
his_conc = total_conc * percentage_unprotonated
print(f"{his_conc = } M")
```

#### (c) Reaction order

The reaction equation for the reaction between  $\text{His}$ and $\text{R}$ is 

$$
v = - \frac{d[\text{His}]}{dt} = k \cdot [\text{His}] \cdot [\text{R}]
$$

What's the reaction order? 

#### (d) High concentrations

If $[\text{R}]$ is much higher than $[\text{His}]$, what can then be concluded regarding the order of the reaction? 

#### (e) New rate constant

Show how a new rate constant, $k'$, can be defined in these conditions. How does $k'$ depend on $\text{R}$?

#### (f) SI Units

At pH 6.0 the reaction rate $v = 1 \ \text{mM}\cdot \text{s}^{-1}$ and constant $[\text{R}] = 0.2 \ \text{M}$

Convert the reaction rate to SI-units given in $\text{M}\cdot \text{s}^{-1}$.

```{python}
#| eval: false
...
```

#### (g) Calculate the rate constant 

Use the concentration of $[\text{His}]$ at pH 6 calculated in question (b) and calculate the rate constant k.

```{python}
#| eval: false
...
```
