
stages:
  - pages

variables:
  PYTHON_VERSION: "3.11"
  BASE_LAYER: "debian"
  UV_LINK_MODE: "copy"
  UV_CACHE_DIR: ".uv-cache"
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PIP_NO_PYTHON_VERSION_WARNING: "1"

.default_uv:
  image: ghcr.io/astral-sh/uv:debian
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends curl ca-certificates make
    # Install Quarto (standalone)
    - wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.8.24/quarto-1.8.24-linux-amd64.tar.gz
    - mkdir ~/opt
    - tar -C ~/opt -xvzf quarto-1.8.24-linux-amd64.tar.gz
    - export PATH="/opt/quarto/bin:$PATH"
    - quarto --version  
  cache:
    - key:
        files: [pyproject.toml, uv.lock]
      paths: [$UV_CACHE_DIR]
  after_script:
    - uv cache prune --ci

pages:
  extends: .default_uv
  stage: pages
  script:
    - uv sync
    - source .venv/bin/activate
    - make website
  publish: _combined_site/
  artifacts:
    paths:
      - _combined_site
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never
