project:
  type: website
  output-dir: _site-combined/student/
  render:
    - index.qmd
    - lessons/*.qmd   # only build the exercises, not other misc files
    - quizzes/*.qmd   # build quizzes too

filters:
  - filters/strip-solution.lua

website:
  title: "Fysisk Biokemi - Python Øvelser"
  search: true
  navbar:
    left:
      - text: Exercises
        href: index.qmd
    right:
      - icon: gitlab
        href: https://gitlab.com/au_mbg/fysisk_biokemi#
  sidebar:
    style: floating
    contents:
      - section: "Exercises"
        contents: lessons/*.qmd
      - section: "Quizzes"
        contents: quizzes/*.qmd
format:
  html:
    toc: true
    toc-depth: 3
    number-sections: false
    code-tools: true
    theme: cosmo

# keep ipynb too if you want downloadable notebooks per page
# (optional; remove if you want HTML-only)
  ipynb: default

execute:
  echo: true
  warning: false
  error: false
