project:
  type: website
  output-dir: _site-combined/student/
  render:
    - index.qmd
    - lessons/*.qmd   # only build the exercises, not other misc files
    - quizzes/*.qmd   # build quizzes too

resource-path:
  - lessons/figures/

filters:
  - at: post-ast
    path: filters/strip-solution.lua

website:
  title: "Fysisk Biokemi - Python Øvelser"
  search: true
  favicon: other/favicon.svg
  navbar:
    left:
      - text: Exercises
        href: index.qmd
    right:
      - icon: github
        href: https://github.com/au-mbg/fysisk-biokemi
  sidebar:
    style: floating
    contents:
      - section: "Exercises"
        contents: lessons/*.qmd
      - section: "Quizzes"
        contents: quizzes/*.qmd
format:
  html:
    toc: true
    toc-depth: 3
    number-sections: false    
    code-tools: true
    theme: cosmo
  ipynb: default
  typst: 
    number-sections: true
    toc: true
    toc-depth: 2

format-links:
  - format: typst
    text: PDF
    icon: file-pdf
  - format: ipynb
    text: Notebook
    icon: journal-code        

execute:
  echo: true
  warning: false
  error: false
  cache: true
