[workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]

[dependencies]
quarto = ">=1.8.27,<2"
python = "3.12.*"

[feature.standard.pypi-dependencies]
fysisk-biokemi = { path = "course-utils", editable = true, extras = ["standard"] }

[feature.dev.pypi-dependencies]
nbformat = ">=5.10.4"
uv = "*"

[environments]
default = { features = ["standard"], solve-group = "default" }
dev = { features = ["standard", "dev"], solve-group = "default" }
standard = { features = ["standard"], solve-group = "default" }

[activation]
env = { TYPST_FONT_PATHS = "$PIXI_PROJECT_ROOT/course/other/fonts" }

[tasks.preview]
args = [{ "arg" = "mode", default = "master", choices = ["student", "master"] }]
cmd = "quarto preview --profile site-{{mode}}"
cwd = "course"
description = "Preview the course notes in either student or master mode"
default-environment = "standard"

[tasks.render]
args = [{ "arg" = "mode", default = "master", choices = ["student", "master"] }]
cmd = "quarto render --profile site-{{mode}},typst"
cwd = "course"
description = "Render the course notes in either student or master mode"
default-environment = "standard"

[tasks.render-all]
depends-on = [
    "_clean",
    { task = "render", args = ["student"] },
    { task = "render", args = ["master"] },
    "_move-index",
]
description = "Clean and render the course notes in both student and master mode"

[tasks._clean]
cmd = """
  rm -rf _site-combined &&
  rm -rf **/*.pdf;
  rm -rf *.html;
  rm -rf lessons/*html lessons/*.ipynb lessons/*_files lessons/.ipynb_checkpoints;
  rm -rf datasets_files/ index_files/
  rm *.ipynb
  """
cwd = "course"
description = "Clean up old build artifacts before rendering"

[tasks._move-index]
cmd = "cp redirect/index.html _site-combined/index.html"
cwd = "course"
description = "Move the index.html to the combined site"

[tasks.build-wheel]
cmd = "rm -rf dist && uv build course-utils --out-dir dist"
description = "Build the course utility package wheel"
default-environment = "dev"
