---
title: Mere om funktioner
engine: jupyter
categories: ["functions", "parentheses"]
format-links:
    - text: "Open in Google Colab"
      href: "https://colab.research.google.com/github/au-mbg/fysisk-biokemi/blob/built-notebooks/built_notebooks/student/notebook_3.ipynb"
      icon: box-arrow-up-right
---

``` {python}
#| eval: false
#| code-fold: true
try:
    import fysisk_biokemi
    print("Already installed")
except ImportError:
    %pip install "fysisk_biokemi[colab] @ git+https://github.com/au-mbg/fysisk-biokemi.git"
```

Vi vil senere i kurset se ligninger som f.eks. den kvadratiske bindings ligning

$$
\theta = \frac{K_D + [P_{tot}] + [L_{tot}]}{2[P_{tot}]} - \sqrt{\left(\frac{K_D + [P_{tot}] + [L_{tot}]}{2[P_{tot}]}\right)^2 - \frac{[L_{tot}]}{[P_{tot}]}},
$$
som kan bruges til at beskrive titreringsdata, der rapporterer proteinets mætning som funktion af den samlede ligandkoncentration.

At regne denne funktion kræver at vi er forsigtige med parenteser! Hvilket vi alle har 
lært, men eftersom det er meget vigtigt i denne sammenhæng er det værd at genopfriske. 

### Opgave 1 

For følgende par af udtryk beregne begge (i hånden eller i hovedet alt efter præference.)

- $2 + 3 \times 4$ vs. $(2 + 3) \times 4$
- $10 - 2^2$ vs. $(10 - 2)^2$
- $100 / 10 \times 2$ vs. $100 / (10 \times 2)$ 
- $\frac{12 + 8}{4}$ vs. $12 + 8 / 4$

### Opgave 2

For de tre beregninger nedenfor overvej hvad resultat er **inden** du kører cellen. 

```{python}
#| exercise: true
#| eval: false
a = 1 + 2 * 3 ** 2
```
```{python}
#| exercise: true
#| eval: false
b = (1 + 2) * 3 ** 2
```
```{python}
#| exercise: true
#| eval: false
c = 1 + 2 * (3 ** 2)
```

```{python}
#| solution: true
a = 1 + 2 * 3 ** 2
```
```{python}
#| solution: true
b = (1 + 2) * 3 ** 2
```
```{python}
#| solution: true
c = 1 + 2 * (3 ** 2)
```

Cellen herunder printer resultat for hver beregning

```{python}
#| eval: false
print(f"{a = }")
print(f"{b = }")
print(f"{c = }")
```

### Opgave 3

Vi vil gerne beregne udtrykket

$$
\frac{a + b}{c + d}
$$

Nogen har implementeret funktionen herunder, men den er forkert - din opgave er at fikse den.

```{python}
#| exercise: true
#| eval: false
def funktion(a, b, c, d):
    return a + b / c + d

resultat_1 = funktion(152, 16, 2, 2)
print(resultat_1)
```

```{python}
#| solution: true
def funktion(a, b, c, d):
    return (a + b) / (c + d)

resultat_1 = funktion(152, 16, 2, 2)
print(resultat_1)
```

### Opgave 4

Det første led af den kvadratiske bindings ligning er 

$$
\frac{K_D + [P_{tot}] + [L_{tot}]}{2[P_{tot}]} = \frac{a + b + c}{2 b}
$$

Færdiggør funktionen nendenfor så den beregner dette udtryk 

```{python}
#| exercise: true
#| eval: false
def første_led(a, b, c):
    return ... # Erstat ... med din kode.

resultat = første_led(100, 2, 66)
print(resultat)
```

```{python}
#| solution: true
def første_led(a, b, c):
    return (a + b + c) / (2 * b)

resultat = første_led(100, 2, 66)
print(resultat)
```
