project:
  type: default
  render:
    - index.qmd
    - datasets.qmd
    - lessons/*.qmd   # only build the exercises, not other misc files

filters:
  - strip-solution
  - colab-link  
  - jupyterlite-link

resources:
  - ../course-utils/src/fysisk_biokemi/datasets/files/**

resource-path:
  - lessons/figures/

website:
  title: "Fysisk Biokemi & Dataanalyse"
  search: true
  favicon: other/favicon.svg
  navbar:
    left:
      - text: Exercises
        href: index.qmd
      - text: Datasets
        href: datasets.qmd
    right:
      - icon: github
        href: https://github.com/au-mbg/fysisk-biokemi
  sidebar:
    style: floating
    expand: true
    contents:
      - section: "Start"
      - lessons/jupyterlite_intro.qmd
      - section: "Exercises"
      - lessons/week_43.qmd
      - lessons/week_44.qmd
      - lessons/week_45.qmd
      - lessons/week_46.qmd
      - lessons/week_47.qmd
      - lessons/week_48.qmd
      - lessons/week_49.qmd




format:
  html:
    toc: true
    toc-depth: 4
    number-sections: true
    number-depth: 2
    code-tools: true
    theme: cosmo
  ipynb: 
    number-sections: true
    number-depth: 2

format-links:
  - html
  - format: typst
    text: PDF
    icon: file-pdf
  - format: ipynb
    text: Notebook
    icon: journal-code        

execute:
  echo: true
  warning: false
  error: false
  freeze: auto


teaching:
  colab:
    repo: au-mbg/fysisk-biokemi
    branch: built-notebooks
    root: built_notebooks
    notebook-profile: student
  jupyterlite:
    url: https://au-mbg.github.io/jupyterlite-playground/lab/index.html
    repo: au-mbg/fysisk-biokemi
    branch: built-notebooks
    root: built_notebooks
    notebook-profile: student
    course-directory: fysisk-biokemi
