project:
  output-dir: _student

filters:
  - filters/strip-solution.lua

format:
  ipynb: default

execute:
  echo: true                   # show starter code
  warning: false
  error: false
  cache: true

