# .github/workflows/pages.yml
name: Quarto → Pages

on:
  push:
    branches: [ "main" ]   # change if your default branch differs

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4


      - uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.18"

      # Quarto CLI (no manual apt/wget needed)
      - uses: quarto-dev/quarto-actions/setup@v2

      - name: uv sync
        shell: bash
        run: uv sync --extra standard

      # Build your site (adjust if your Makefile target differs)
      - name: Build site
        shell: bash
        run: |
          source .venv/bin/activate
          cd course
          make website
          
      # Upload the built site folder
      - uses: actions/upload-pages-artifact@v3
        with:
          path: course/_site-combined

      - uses: actions/checkout@v5
        with:
          ref: built-notebooks
          clean: false

      - name: gather notebooks
        shell: bash
        run: |
          mkdir -p built_notebooks
          mkdir -p built_notebooks/student
          mkdir -p built_notebooks/master
          cp course/_site-combined/student/lessons/*.ipynb built_notebooks/student/.
          cp course/_site-combined/master/lessons/*.ipynb built_notebooks/master/.

      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: 'built_notebooks/*'
          default_author: github_actor
          message: 'Update notebooks'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4